Repository ProjectNeura/LEADS, pull requests merged in 2024-05, with the labels that each got.

#127 Automate Reverse Proxy Setup
  README.md
  leads_gui/system.py
  leads_raspberry_pi/led_group.py
  leads_vec/__main__.py
  leads_vec/_bootloader/__init__.py
  leads_vec/_bootloader/frp.py
  scripts/frp-config.sh
  scripts/frp-install.sh
  scripts/obs-install.sh
  scripts/obs-run.sh
  scripts/python-install.sh
  scripts/setup.sh
Labels: enhancement, todo

#128 Include `pysdl2-dll` in the Optional Dependencies
  leads_audio/__init__.py
Labels: documentation, enhancement, todo

#132 Improve `leads_vec` Debugging Information
  leads_vec/__main__.py
  leads_vec/_bootloader/frp.py
Labels: enhancement, todo

#134 ImportError: cannot import name 'getuid' from 'os'. Did you mean: 'getpid'?
  leads_vec/__main__.py
  leads_vec/_bootloader/systemd.py
Labels: bug, todo

#129 Add Configuation for OBS Studio
  design/obs-config.json
Labels: enhancement, report, todo

#135 OBS Studio Fails to Initialize
  scripts/obs-run.sh
Labels: bug, report, todo

#137 Fix the Invalid OBS Studio Layout Configuation
  design/obs-config.json
Labels: bug, todo

#141 `setup.sh` Exits Unexpectedly
  scripts/setup.sh
Labels: bug, todo

#147 Error: /usr/bin/python-leads: No module named leads_vec
  scripts/python-install.sh
  scripts/setup.sh
Labels: bug, todo

#149 FileExistsError: [Errno 17] File exists: '/usr/local/leads'
  leads_vec/_bootloader/systemd.py
Labels: bug, todo

#153 OSError: [Errno 6] No such device or address
  leads_vec/_bootloader/leads_vec.service.sh
Labels: bug, todo

#152 No Display Environment when the Systemd Service Initializes
  README.md
  leads_audio/prototype.py
  leads_vec/_bootloader/leads_vec.service.sh
  leads_vec/_bootloader/systemd.py
  scripts/frp-config.sh
  scripts/frp-install.sh
  scripts/obs-install.sh
  scripts/obs-run.sh
  scripts/python-install.sh
  scripts/setup.sh
Labels: bug, todo

#155 Systemd Service Permission Denied
  leads_vec/_bootloader/leads_vec.service.sh
  leads_vec/_bootloader/systemd.py
  scripts/frp-config.sh
  scripts/frp-install.sh
  scripts/obs-install.sh
  scripts/obs-run.sh
  scripts/python-install.sh
  scripts/setup.sh
Labels: bug, todo

#160 Failed to enable unit: Unit file /home/projectneura/.config/systemd/user/default.target.wants/leads-vec.service does not exist
  leads_vec/_bootloader/systemd.py
Labels: bug, todo

#166 Add Private Credentials to a Private Repository
  leads_vec/__init__.py
  leads_vec/__main__.py
  leads_vec/cli.py
  leads_vec/replay.py
  leads_vec/run.py
Labels: enhancement, todo

#167 Support Custom Main Functions
  README.md
  leads_vec/__main__.py
  leads_vec/run.py
Labels: enhancement, todo

#169 Error Data Output File
  leads_vec_rc/cli.py
Labels: bug, todo

#172 Incorrect Hazard Light Logic
  leads/context.py
  leads/event.py
  leads/leads.py
Labels: bug, todo

#176 Devices are not Properly Closed
  leads/__init__.py
  leads/dt/registry.py
  leads/os.py
  leads_audio/prototype.py
  leads_vec/run.py
  leads_vec_rc/cli.py
Labels: bug, todo

#177 Add Postprocess Analysis
  leads/config/template.py
  leads/context.py
  leads/data.py
  leads/data_persistence/__init__.py
  leads/data_persistence/_computational/__init__.py
  leads/data_persistence/core.py
  leads/data_persistence/pp.py
  leads/dt/odometer.py
  leads/os.py
  leads/plugin/gps_speed_correction.py
  leads/plugin/plugin.py
  leads_arduino/wheel_speed_sensor.py
  leads_emulation/replay.py
  leads_gui/accelerometer.py
  leads_gui/prototype.py
  leads_raspberry_pi/gps_receiver.py
  leads_vec/cli.py
  leads_vec/replay.py
  leads_vec_rc/cli.py
Labels: enhancement, report, todo

#181 Serial Port Permission Denied
  leads_vec/_bootloader/systemd.py
Labels: bug, todo

#187 Permission Denied when Executing `setup.sh`
  scripts/setup.sh
Labels: bug, todo

#189 Group "dialoutusername" does not Exist
  leads_vec/_bootloader/systemd.py
Labels: bug, todo

#199 Support Multiple Magnets on the Wheel
  leads_arduino/wheel_speed_sensor.py
  leads_vec/devices.py
Labels: enhancement, todo

#200 Support GPS Only Mode
  leads_vec/devices.py
Labels: enhancement, report, todo

#202 Use `match` Instead of `if` Trees
  leads_raspberry_pi/led.py
  leads_raspberry_pi/led_group.py
  leads_vec/cli.py
  leads_vec/run.py
Labels: enhancement, code review, todo
