Repository ProjectNeura/LEADS, pull requests merged in 2025-03, with the labels that each got.

#477 Fastening Issue with the Main Controller Case Top Cover
  design/main_controller.c4d
  design/main_controller.stl
Labels: bug, todo

#479 Add Parallel Connection Holes for the Main Controller Case
  design/main_controller.c4d
  design/main_controller.stl
Labels: enhancement, todo

#480 Support Pedals as Built-in Devices
  arduino/leads_vec_power/Pedal.h
  arduino/leads_vec_power/leads_vec_power.ino
Labels: enhancement, report, todo

#481 Support Pedals as Built-in Devices
  arduino/leads_vec_power/Pedal.cpp
  arduino/leads_vec_power/Pedal.h
  arduino/leads_vec_power/leads_vec_power.ino
  leads_arduino/__init__.py
  leads_arduino/pedal.py
Labels: enhancement, report, todo

#484 Merge `leads_vec_power/Pedal` and `leads_vec_wsc/Accelerometer` into LEADS-Arduino
  arduino/leads_vec_power/Pedal.cpp
  arduino/leads_vec_power/Pedal.h
  arduino/leads_vec_wsc/Accelerometer.h
  arduino/leads_vec_wsc/Adafruit_BNO08x_RVC.cpp
  arduino/leads_vec_wsc/Adafruit_BNO08x_RVC.h
  arduino/leads_vec_wsc/BNO08x.cpp
  arduino/leads_vec_wsc/BNO08x.h
  arduino/leads_vec_wsc/leads_vec_wsc.ino
Labels: enhancement, code review, todo

#488 Use Scientific Notations for Small Float Numbers
  leads/comm/prototype.py
  leads/data_persistence/analyzer/inference.py
  leads/data_persistence/analyzer/processor.py
  leads/ltm.py
  leads_arduino/wheel_speed_sensor.py
  leads_comm_serial/connection.py
  leads_gui/performance_checker.py
  leads_video/utils.py
Labels: code review, todo
